package com.rox.emu.p6502;

public enum OpCode {
            OP_ASL_A(0x0A,"ASL (Accumulator)"),
            OP_ASL_Z(0x06,"ASL (Zero Page)"),
            OP_ASL_ABS(0x0E,"ASL (Absolute)"),
            OP_ASL_Z_IX(0x16,"ASL (Zero Page[X]"),
            OP_ASL_ABS_IX(0x1E,"ASL (Zero Page[Y]"),
            OP_LSR_A(0x4A,"LSR (Accumulator)"),
            OP_LSR_Z(0x46,"LSR (Zero Page)"),
            OP_LSR_Z_IX(0x56,"LSR (Zero Page[X])"),
            OP_LSR_ABS(0x4E,"LSR (Absolute)"),
            OP_LSR_ABS_IX(0x5E,"LSR (Absolute[X])"),
            OP_ADC_Z(0x65,"EMPTY"),
            OP_ADC_I(0x69,"EMPTY"),
            OP_ADC_ABS(0x6D,"EMPTY"),
            OP_ADC_ABS_IX(0x7D,"EMPTY"),
            OP_ADC_ABS_IY(0x79,"EMPTY"),
            OP_ADC_Z_IX(0x75,"EMPTY"),
            OP_LDA_Z(0xA5,"EMPTY"),
            OP_LDA_I(0xA9,"EMPTY"),
            OP_LDA_ABS(0xAD,"EMPTY"),
            OP_LDA_Z_IX(0xB5,"EMPTY"),
            OP_LDA_ABS_IY(0xB9,"EMPTY"),
            OP_LDA_IND_IX(0xA1,"EMPTY"),
            OP_LDA_ABS_IX(0xBD,"EMPTY"),
            OP_CLV(0xB8,"EMPTY"),
            OP_AND_Z(0x25,"EMPTY"),
            OP_AND_Z_IX(0x35,"EMPTY"),
            OP_AND_ABS_IX(0x3D,"EMPTY"),
            OP_AND_ABS_IY(0x39,"EMPTY"),
            OP_AND_ABS(0x2D,"EMPTY"),
            OP_AND_I(0x29,"EMPTY"),
            OP_ORA_I(0x09,"EMPTY"),
            OP_ORA_Z(0x05,"EMPTY"),
            OP_ORA_Z_IX(0x15,"EMPTY"),
            OP_ORA_ABS(0x0D,"EMPTY"),
            OP_ORA_ABS_IX(0x1D,"EMPTY"),
            OP_EOR_I(0x49,"EMPTY"),
            OP_EOR_Z(0x45,"EMPTY"),
            OP_EOR_Z_IX(0x55,"EMPTY"),
            OP_EOR_ABS(0x4D,"EMPTY"),
            OP_EOR_ABS_IX(0x5D,"EMPTY"),
            OP_SBC_I(0xE9,"EMPTY"),
            OP_SBC_Z(0xE5,"EMPTY"),
            OP_SBC_Z_IX(0xF5,"EMPTY"),
            OP_SBC_ABS(0xED,"EMPTY"),
            OP_SBC_ABS_IX(0xFD,"EMPTY"),
            OP_SBC_ABS_IY(0xF9,"EMPTY"),
            OP_CLC(0x18,"EMPTY"),
            OP_SEC(0x38,"EMPTY"),
            OP_LDY_I(0xA0,"EMPTY"),
            OP_LDY_Z(0xA4,"EMPTY"),
            OP_LDY_Z_IX(0xB4,"EMPTY"),
            OP_LDY_ABS(0xAC,"EMPTY"),
            OP_LDY_ABS_IX(0xBC,"EMPTY"),
            OP_LDX_I(0xA2,"EMPTY"),
            OP_LDX_ABS(0xAE,"EMPTY"),
            OP_LDX_ABS_IY(0xBE,"EMPTY"),
            OP_LDX_Z(0xA6,"EMPTY"),
            OP_LDX_Z_IY(0xB6,"EMPTY"),
            OP_STY_Z(0x84,"EMPTY"),
            OP_STY_ABS(0x8C,"EMPTY"),
            OP_STY_Z_IX(0x94,"EMPTY"),
            OP_STA_Z(0x85,"EMPTY"),
            OP_STA_ABS(0x8D,"EMPTY"),
            OP_STA_Z_IX(0x95,"EMPTY"),
            OP_STA_ABS_IX(0x9D,"EMPTY"),
            OP_STA_ABS_IY(0x99,"EMPTY"),
            OP_STX_Z(0x86,"EMPTY"),
            OP_STX_Z_IY(0x96,"EMPTY"),
            OP_STX_ABS(0x8E,"EMPTY"),
            OP_INY(0xC8,"EMPTY"),
            OP_INC_Z(0xE6,"EMPTY"),
            OP_INC_Z_IX(0xF6,"EMPTY"),
            OP_INC_ABS(0xEE,"EMPTY"),
            OP_INC_ABS_IX(0xFE,"EMPTY"),
            OP_DEC_Z(0xC6,"EMPTY"),
            OP_DEC_Z_IX(0xD6,"EMPTY"),
            OP_DEC_ABS(0xCE,"EMPTY"),
            OP_DEC_ABS_IX(0xDE,"EMPTY"),
            OP_DEY(0x88,"EMPTY"),
            OP_INX(0xE8,"EMPTY"),
            OP_DEX(0xCA,"EMPTY"),
            OP_PHA(0x48,"EMPTY"),
            OP_PLA(0x68,"EMPTY"),
            OP_NOP(0xEA,"EMPTY"),
            OP_JMP_ABS(0x4C,"EMPTY"),
            OP_TAX(0xAA,"EMPTY"),
            OP_TAY(0xA8,"EMPTY"),
            OP_TYA(0x98,"EMPTY"),
            OP_TXA(0x8A,"EMPTY"),
            OP_TXS(0x9A,"EMPTY"),
            OP_TSX(0xBA,"EMPTY"),
            OP_BIT_Z(0x24,"EMPTY"),
            OP_BIT_ABS(0x2C,"EMPTY"),

            OP_CMP_I(0xC9,"EMPTY"),
            OP_CMP_Z(0xC5,"EMPTY"),
            OP_CMP_Z_IX(0xD5,"EMPTY"),
            OP_CMP_ABS(0xCD,"EMPTY"),
            OP_CMP_ABS_IX(0xDD,"EMPTY"),
            OP_CMP_ABS_IY(0xD9,"EMPTY"),
            OP_CPX_I(0xE0,"EMPTY"),
            OP_CPX_Z(0xE4,"EMPTY"),
            OP_CPX_ABS(0xEC,"EMPTY"),
            OP_CPY_I(0xC0,"EMPTY"),
            OP_CPY_Z(0xC4,"EMPTY"),
            OP_CPY_ABS(0xCC,"EMPTY"),
            OP_PHP(0x08,"EMPTY"),
            OP_PLP(0x28,"EMPTY"),

            OP_JSR(0x20,"EMPTY"),
            OP_BPL(0x10,"EMPTY"),
            OP_BMI(0x30,"EMPTY"),
            OP_BVC(0x50,"EMPTY"),
            OP_BVS(0x70,"EMPTY"),
            OP_BCC(0x90,"EMPTY"),
            OP_BCS(0xB0,"EMPTY"),
            OP_BNE(0xD0,"EMPTY"),
            OP_BEQ(0xF0,"EMPTY"),

            OP_ROL_A(0x2A,"EMPTY"),
            OP_ROL_Z(0x26,"EMPTY"),
            OP_ROL_Z_IX(0x36,"EMPTY"),
            OP_ROL_ABS(0x2E,"EMPTY"),
            OP_ROL_ABS_IX(0x3E,"EMPTY"),

            OP_ROR_A(0x6A,"EMPTY"),

            OP_CLI(0x58,"EMPTY"),
            OP_SEI(0x78,"EMPTY"),
            OP_SED(0xF8,"EMPTY"),
            OP_CLD(0xD8,"EMPTY");

    private int byteValue;
    private String description;

    public int getByteValue(){
        return byteValue;
    }

    OpCode(int byteValue, String description){
        this.byteValue = byteValue;
        this.description = description;
    }
}
